### ISSUE TITLE
Dockerizing project

### ISSUE THREAD

**Issue by SonnyX** [DakuTree/manga-tracker#357]
## Feature/Site Request
**What is the feature?**
Write how to run the server in the wiki by setting up a Dockerfile so that developers can work on adding sites without guessing, testing the actual code before commiting, without having to clutter their operating system with packages they won't ever use again.

This so that something as below can be used:

`Clone repository to directory, cd into directory, add your changes, create Dockerfile with the content below:`
```
FROM php:7.2.6-apache
WORKDIR /var/www/html
COPY . /var/www/html
#More commands that actually autoconfigure the webserver
```
`sudo docker build -t manga-tracker .`
`sudo docker run --rm -p 8080:80 --name running-manga-tracker manga-tracker`
IP can be found in the terminal, open address in browser, test out a manual update.

**Comment by SonnyX** [comment]
Had to change `RUN apt-get update && apt-get upgrade -y` to 
```
RUN apt update && apt upgrade -y
RUN apt install -y git unzip
```

Besides for anybody also trying to build along, the commands are:
```
chmod +x .docker/wait-for-it.sh
sudo docker-compose build
sudo docker-compose up
```

However it won't fully work yet at this point since the files being build are being overwritten by the shared volume in the `docker-compose.yml`, therefor changed
```
    volumes:
      - .:/app
```
to 
```
    volumes:
      - ./public:/app/public
```
This gets it close to running, however still gives some issues regarding monolog

**Comment by DakuTree** [comment]
Added `RUN apt install -y git unzip` & `RUN chmod +x .docker/wait-for-it.sh` to the dockerfile.

Unsure what exactly is causing the monolog issue. Only seems to occur when the volume is changed to `./public:/app/public`, while it works fine when using `.:/app`.

**Comment by SonnyX** [comment]
You are correct, it may be from me having tried to get it to work before where I somehow messed up somewhere. However using the latest commit I get when opening the page:
```
Warning: socket_sendto(): Host lookup failed [-10003]: Unknown server error in /app/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php on line 47

Warning: socket_sendto(): Host lookup failed [-10003]: Unknown server error in /app/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php on line 47

Warning: socket_sendto(): Host lookup failed [-10003]: Unknown server error in /app/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php on line 47

Warning: socket_sendto(): Host lookup failed [-10003]: Unknown server error in /app/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php on line 47

Fatal error: Uncaught UnexpectedValueException: The stream or file "/app/application//logs/ci-2018-06-12.log" could not be opened: failed to open stream: Permission denied in /app/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 Stack trace: #0 /app/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\Handler\StreamHandler->write(Array) #1 /app/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array) #2 /app/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array) #3 /app/vendor/monolog/monolog/src/Monolog/Logger.php(404): Monolog\Logger->addRecord(400, 'Severity: Warni...', Array) #4 /app/application/core/MY_Log.php(173): Monolog\Logger->addError('Severity: Warni...') #5 /app/vendor/codeigniter/framework/system/core/Common.php(469): MY_Log->write_log('ERROR', 'Severity: Warni...') #6 /app/vendor/codeigniter/framework/system/core/Exceptions.php(105): log_mes in /app/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

Warning: socket_sendto(): Host lookup failed [-10003]: Unknown server error in /app/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php on line 47

Warning: socket_sendto(): Host lookup failed [-10003]: Unknown server error in /app/vendor/monolog/monolog/src/Monolog/Handler/SyslogUdp/UdpSocket.php on line 47

Fatal error: Uncaught UnexpectedValueException: The stream or file "/app/application//logs/ci-2018-06-12.log" could not be opened: failed to open stream: Permission denied in /app/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 Stack trace: #0 /app/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\Handler\StreamHandler->write(Array) #1 /app/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array) #2 /app/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array) #3 /app/vendor/monolog/monolog/src/Monolog/Logger.php(404): Monolog\Logger->addRecord(400, 'Severity: Warni...', Array) #4 /app/application/core/MY_Log.php(173): Monolog\Logger->addError('Severity: Warni...') #5 /app/vendor/codeigniter/framework/system/core/Common.php(469): MY_Log->write_log('ERROR', 'Severity: Warni...') #6 /app/vendor/codeigniter/framework/system/core/Exceptions.php(105): log_mes in /app/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107
```

**Comment by SonnyX** [comment]
Using the following volumes I can actually get it to display the page:
```
    volumes:
      - ./application:/app/application
      - ./public:/app/public
      - ./_scripts:/app/_scripts
```

**Comment by DakuTree** [comment]
> You mentioned you added the unzip to the install, however you added the zip package, sadly this results in the following error for me:  
> ...

Seems like the zip php ext was needed here rather than the apt package. No longer appears to be erroring with the new DockerFile.


> Here are the two error messages (which are shown multiple times):  
> ...socket_sendto(): Host lookup failed [-10003]: Unknown server error...  
> ...stat failed for /app/application/../public/assets/css/main.light.css...

First issue seems to be to us trying to connect to papertrail (even though we aren't using it), that just needs to be removed. Second issue really shouldn't be happening on dev as we don't use the theme css.  
Both are easy fixes, but since .dockerignore refuses to work properly it's been difficult to actually test it (since it keeps including my local monolog config & compiled css).  

.dockerignore only appears to be properly ignoring root files, anything in subdirectories don't appear to ignore properly. Unsure if this is a weird bug or if I'm doing something completely wrong here.

Got a .dockerignore only containing:
 ```
README.md
public/assets/css/
!public/assets/css/.gitkeep
```

Appended `RUN ls -a /app/public/assets/css/` below the WORKDIR line in the web.DockerFile.  
ls returns only .gitkeep, no compiled files (which I have locally).  
After build I run `docker-compose rm -v && docker-compose run web ls public/assets/css`, which shows the compiled css files (main.dark.css, main.light.css) still existing, however the README.md file which was also ignored doesn't exist.

**Comment by SonnyX** [comment]
@DakuTree This is due to the 
```
     volumes:
      - ./application:/app/application
      - ./public:/app/public
      - ./_scripts:/app/_scripts
```
This does not share any files in the head `./` directory but only shares three of five subdirectories, namely application, public and _scripts, all files and directories in these subfolders are being shared **only** while running the `web` service, not while building the `web` service. That is why you do not see your local files during the build process (since the `.dockerignore` at that time is in effect and works) however only see them while running the service (and thus the volumes mentioned above are shared), since at that time the docker internal filesystem is simply being bound to the external file system directly.

Also a script to clear out/remove ALL non-tagged docker images and non-running containers, not restricted by only a certain project:
```
#!/bin/bash
docker rm $(docker ps -qa --no-trunc --filter "status=exited")
docker rmi $(docker images -q --no-trunc --filter "dangling=true")
```

**Comment by SonnyX** [comment]
Looking at the created files might give a good indication as to what should be included from the user, as to what should be left out.

I modified the `web.Dockerfile` to something more efficient for repeated builds and am now showing the created files using GIT:
```
FROM php:7.2-apache

# Note: We do not need to upgrade here.
RUN apt-get update --quiet
RUN apt-get install --quiet --yes --no-install-recommends git zlib1g-dev

RUN docker-php-ext-install \
 pdo \
 pdo_mysql \
 mysqli \
 sockets \
 zip

COPY . /app
WORKDIR /app
COPY ./.docker/vhost.conf        /etc/apache2/sites-available/001-localhost.conf
COPY ./.docker/vhost-static.conf /etc/apache2/sites-available/001-static.localhost.conf
RUN a2dissite 000-*
RUN a2ensite 001-*

RUN a2enmod \
 rewrite \
 expires \
 headers

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN composer global require hirak/prestissimo
RUN composer install --no-interaction

# Required for init
RUN chmod +x .docker/wait-for-it.sh

RUN rm .gitignore
RUN git config --global user.email "local@docker.build"
RUN git config --global user.name "Docker Build System"
RUN git add -A
RUN git commit -m "Files created during build"
```

**Comment by DakuTree** [comment]
> ...since at that time the docker internal filesystem is simply being bound to the external file system directly.

Ahh that makes a lot more sense. I was thinking that volumes only shared between containers, not the external file system as well.  
This is my first time using Docker so it's been a lot of trial and error.

> I modified the web.Dockerfile to something more efficient for repeated builds and am now showing the created files using GIT:

Didn't realize it cached after each command. That certainly helps make things more efficient.  
Merged your changes (except the git tweaks) and also tweaked the composer install to take advantage of that as well (which hopefully doesn't cause any issues).

**Comment by SonnyX** [comment]
So I see, sharing the volumes wouldn't be a hard requirement in my opinion since commands such as `docker-compose up --build` exist, if the build process is efficient enough (caching everything except copying the files as the last step).
I however haven't been able to come past the error of 
```
 Fatal error: Uncaught UnexpectedValueException: There is no existing directory at "/app/application//logs" and its not buildable: Permission denied in /app/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:171 Stack trace: #0 /app/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir() #1 /app/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(107): Monolog\Handler\StreamHandler->write(Array) #2 /app/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array) #3 /app/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array) #4 /app/vendor/monolog/monolog/src/Monolog/Logger.php(518): Monolog\Logger->addRecord(400, 'Uncaught Except...', Array) #5 /app/vendor/monolog/monolog/src/Monolog/ErrorHandler.php(136): Monolog\Logger->log(400, 'Uncaught Except...', Array) #6 [internal function]: Monolog\ErrorHandler->handleException(Object in /app/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 171
```
This shows that it is not able to find `/app/applications//logs`, making sure the path is "more correct" by editing /app/applications/config/monolog.php by changing `$config['file_logfile'] = APPPATH.'/logs/ci.log';` to `$config['file_logfile'] = APPPATH.'logs/ci.log';` and `$config['ci_file_logfile'] = APPPATH.'/logs/log.php';` to `$config['ci_file_logfile'] = APPPATH.'logs/log.php';` does not fix it either, neither does generating the directory in the web.Dockerfile during build.

**Comment by SonnyX** [comment]
```
    volumes:
      - ./application/config:/app/application/config
      - ./application/models/Tracker:/app/application/models/Tracker
      - ./application/tests/models/Tracker/Sites:/app/application/tests/models/Tracker/Sites
      - ./application/views:/app/application/views
      - ./public/assets/img:/app/public/assets/img
      - ./public/assets/less/modules:/app/public/assets/less/modules
      - ./public/userscripts:/app/userscripts
```

**Comment by DakuTree** [comment]
> One another thing that would be useful is a general admin login in the devel environment if it is not there yet.

The ion_auth migration adds a default login.  
User: `administrator` / Pass: `password`

**Comment by DakuTree** [comment]
> I believe these migration scripts get executed automatically, right?

Yeah they do.

> The system seems to be accepting the combination, redirecting me to the front page, however I don't think I can access anything at that point.

This should be fixed as of 11d094c6ecaa6dbf70d0c8a97ec64ed507345936 & 87e6af06947a9d619c2747963c75fd950ece5420.

**Comment by SonnyX** [comment]
Nice, these commits indeed allow me to log in now :+1:
